services:
  # Веб-сервер с PHP приложением
  web:
    build: ./web
    container_name: OnlyTestWeb
    ports:
      - "8080:80" 
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db  #зависимость от БД
    networks:
      - app_network
    environment:
      # подключения к БД
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: OnlyTestDB
      DATABASE_USER: root
      DATABASE_PASSWORD: strong_password_123
    restart: unless-stopped

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: OnlyTestDB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strong_password_123
      MYSQL_DATABASE: OnlyTestDB
      MYSQL_USER: app_user_dev
      MYSQL_PASSWORD: strong_password_123
    volumes:
      - ./DataBase/data:/var/lib/mysql 
      - ./DataBase/Default:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" 
    networks:
      - app_network
    command: 
      - --default-authentication-plugin=mysql_native_password 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: OnlyTestPMA
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: strong_password_123
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
    ports:
      - "8081:80" 
    networks:
      - app_network
    depends_on:
      - db

# Общая сеть для контейнеров
networks:
  app_network:
    driver: bridge