services:
  # Веб-сервер с PHP приложением
  web:
    build: ./web
    container_name: teacher_competence
    ports:
      - "8080:80"  # Пробрасываем на порт 8080 хоста
    volumes:
      - ./web:/var/www/html  # Монтируем код проекта
    depends_on:
      - db  # Указываем зависимость от БД
    networks:
      - app_network
    environment:
      # Переменные для подключения к БД
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: teacherCompetence
      DATABASE_USER: root
      DATABASE_PASSWORD: strong_password_123
      JWT: YeJLz7slFawiR3NHdt7HPJVgsWv8WQifxvMFLz3pdgatvSGRxiK5mioA0rXKNNUIjppHMp5vRibPIdXRQabdvYgFTlvR9n0SbA4j2xs85lPozEYxo81tvUvmRNcwrOn1XobleUSjza2AI1b6GOsWLhIOB2SwhhYME1Vyyq0fCV0VFMpSut9agWgOzVWrOUnSjvspRnJ2hnnRTUqdReA8eSx8Sfxpxe8rgVe1zL7qgB5NlPcr18GfTVx0jfLLPLXf
    restart: unless-stopped

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: teacher_competence_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strong_password_123
      MYSQL_DATABASE: teacherCompetence
      MYSQL_USER: app_user_dev
      MYSQL_PASSWORD: strong_password_123
    volumes:
      - ./db/data:/var/lib/mysql 
      - ./DefaultSQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" 
    networks:
      - app_network
    command: 
      - --default-authentication-plugin=mysql_native_password 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: teacher_competence_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: strong_password_123
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
    ports:
      - "8081:80" 
    networks:
      - app_network
    depends_on:
      - db

# Общая сеть для контейнеров
networks:
  app_network:
    driver: bridge