propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=localhost;port=3306;dbname=teacherCompetence
                user: root
                password: 
                settings:
                  charset: utf8
    runtime:
        defaultConnection: default
        connections:
            - default
    generator:
        defaultConnection: default
        connections:
            - default
    paths:
        schemaDir: propel/schema
        outputDir: propel/generated/classes
        phpDir: src/classes/Models
        migrationDir: propel/migrations
        sqlDir: propel/generated/sql
        configDir: propel/generated/conf
